---
title: "Individual Project Summary 3/13"
author: "Yoni Ackerman"
output: pdf_document
bibliography: library.bib
---

# Introduction

Despite alternative facts to the contrary, rapid, anthropogenic climate change is
not only real, but arguably the most dangerous threat (in the mid- to long-term)
facing human societies [@UCS2000]. Given this unprecedented challenge, climate
scientists have developed computational models to predict spatio-temporal
changes in global climate under a variety of scenarios and assumptions [@Hawkins2009].
Using these models in any analysis that goes beyond imagining apocalyptic futures,
however, comes with considerable caveats. For one, estimates of model uncertainty
do not necessarily indicate actual climate uncertainty. The models (in our case CMIP5
models) often share both code modules as well as the biases of their implementors.
Thus the models, and their outputs do not represent independent draws from the space
of "all possible future climates". Because of this, combining the models in the hopes
of developing a "consensus climate" becomes statistically untenable [@Knutti2010].
Moreover, crafting policy based on any such consensus will imply a sense of certainty
that we cannot reasonably expect [@Larose2005]. 

The question then becomes: what can we do with these data? The most interesting option
we have found so far is described in [@Knutti2010]. In this work, the authors attempt
to describe a method of constructing a consensus model (a combination of the models)
that takes into account their interdependence.

They expand ("flatten") the
model outputs (which are multidimensional arrays) into 1D vectors, then concatenate
the vectors of six variables together (TS PR RSUT RLUT T RH) so that each model is
represented by a single row vector in an general model-matrix. They then perform
PCA to limit the model matrix to only orthogonal columns, and finally perform
an MDS on the rows of this new matrix.

Because their study includes a set of observational
data, collected (and subsequently regrided for comparison to CMIP data) from a
variety of sources, that allows them to go another step futher. They define a
grid of points over the MDS space then use the distances of the MDS-space distance
between observation and model points to try to define a prior over this space. This
can then be used to draw independent samples from the MDS space and work backwards
to turn that sample into a consensus model. Furthermore, they build a way to
describe the overall behavior of that model by defining a new quantity for each
model called Climate Sensitivity ("the equilibrium global mean surface temperature 
response to a doubling of carbon dioxide"). They then interpolate this quantity
over MDS space, allowing them to assign any point sampled from there to be immediately
assigned a Climate Sensitivity value.


# Issues

# Current Results

# Anticipated Directions

# References
